db:
  image: mariadb
  ports:
    - "8082:3306"
  environment:
    MYSQL_ROOT_PASSWORD: p@ssword

wp-main:
  image: wordpress
  volumes:
    - ./:/var/www/html
  ports:
    - "8080:80"
  links:
    - db:mysql
  environment:
    WORDPRESS_DB_PASSWORD: p@ssword

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  ports:
    - "8081:80"
  links:
    - db:db